// background.js
chrome.runtime.onInstalled.addListener(async ({ reason }) => {
  if (reason === 'install' || reason === 'update') {
    // Check if API key exists
    const { apiKey } = await chrome.storage.sync.get(['apiKey']);

    if (!apiKey) {
      // Open options page to set API key
      chrome.runtime.openOptionsPage();
    }
  }

  // Set default settings
  await chrome.storage.sync.set({
    apiKey: '',
    autoSaveQuiz: true,
    enableCopyPaste: true,
    theme: 'dark'
  });
});

// Handle messages
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  switch (request.type) {
    case 'OPEN_OPTIONS':
      chrome.runtime.openOptionsPage();
      sendResponse({ success: true });
      break;

    case 'GET_API_KEY':
      chrome.storage.sync.get(['apiKey'], (result) => {
        sendResponse({ apiKey: result.apiKey });
      });
      return true;

    case 'GET_SETTINGS':
      chrome.storage.sync.get(['autoSelect', 'autoSaveQuiz', 'enableCopyPaste'], (result) => {
        sendResponse({
          autoSelect: result.autoSelect !== false,
          autoSaveQuiz: result.autoSaveQuiz !== false,
          enableCopyPaste: result.enableCopyPaste !== false
        });
      });
      return true;

    case 'SAVE_QUIZ_DATA':
      chrome.storage.local.get(['quizData'], (result) => {
        const quizData = result.quizData || [];
        quizData.push(request.data);
        chrome.storage.local.set({ quizData });
        sendResponse({ success: true });
      });
      return true;

    case 'SAVE_QUIZ_WITH_AI':
      chrome.storage.local.get(['aiQuizzes'], (result) => {
        const aiQuizzes = result.aiQuizzes || [];
        aiQuizzes.push(request.data);
        chrome.storage.local.set({ aiQuizzes });
        sendResponse({ success: true });
      });
      return true;

    case 'DOWNLOAD_PDF':
      generatePDF(request.data).then(pdfBlob => {
        const url = URL.createObjectURL(pdfBlob);
        chrome.downloads.download({
          url: url,
          filename: request.filename || `VU_Quiz_${Date.now()}.pdf`
        });
        sendResponse({ success: true });
      }).catch(error => {
        sendResponse({ success: false, error: error.message });
      });
      return true;
  }
});


async function generatePDF(data) {
  // Create a simple PDF using jsPDF
  return new Promise((resolve, reject) => {
    try {
      // Create a simple text-based PDF
      const pdfContent = `
                VU Empire Genie - Quiz Solution
                ================================
                
                Course: ${data.courseName}
                Date: ${new Date(data.timestamp).toLocaleString()}
                
                Question:
                ${data.question}
                
                Options:
                ${data.options.map((opt, i) => `${String.fromCharCode(65 + i)}. ${opt.text}`).join('\n')}
                
                AI Solution:
                ${data.solution?.explanation || 'No explanation provided.'}
                
                Correct Answer(s):
                ${data.solution?.correctAnswers?.join(', ') || 'Not available'}
                
                Generated by VU Empire Genie with Gemini AI
            `;

      const blob = new Blob([pdfContent], { type: 'application/pdf' });
      resolve(blob);
    } catch (error) {
      reject(error);
    }
  });
}